### ISSUE TITLE
Implement chrome.sockets.tcp.secure

### ISSUE THREAD

**Issue by tanx** [MobileChromeApps/mobile-chrome-apps#269]
Good news. Chrome socket is getting native TLS support in Chrome 38: https://developer.chrome.com/apps/socket#method-secure

We have gone ahead and added support to our tcp-socket shim and tested this in chrome canary: https://github.com/whiteout-io/tcp-socket/blob/7f88ffe0ce5f33a22a1489f3bcaa2e9d0bd6474d/src/tcp-socket.js#L247

It would be great to see this api come to iOS/Android as well since native TLS would obviously be much faster and battery conserving.

Thanks!

**Comment by felixhammerl** [comment]
[i already asked this on twitter](https://twitter.com/felixhammerl/status/571325009693507584), apparently the issue has been silently purged? can you confirm this? is google abandoning tcp sockets in chrome apps?

**Comment by mmocny** [comment]
I think it was a mistake. I've posted a question about it.  Not sure what's
up.

**Comment by tanx** [comment]
Any update on the `chrome.sockets.tcp.secure` bug?

The chromium issue url (https://code.google.com/p/chromium/issues/detail?id=403076) seems to be broken. But it's still visible in the chromium-bugs google group:

https://groups.google.com/a/chromium.org/forum/#!topic/chromium-bugs/i9qykTWzj6g

This has been a problem for us a while now, since we can't switch to the native TLS stack on iOS and android because of it. We already bugged Matt Gaunt from the Chrome Team when he was in Munich (https://twitter.com/tankredhase/status/573243929333776384). It would be great if someone from the CCA team could also drive this issue from your side :/

thanks

**Comment by agrieve** [comment]
Thanks for the poke.

Seems its disappearance was in fact a mistake done by an unhelpful bot. I've created a new (public) issue to continue tracking the status of it:
https://code.google.com/p/chromium/issues/detail?id=467677

We'll hopefully get an update about the status soon.

Going to mark this issue as closed since `secure` was actually implemented on iOS and Android, but feel free to open a new issue for things.

**Comment by tanx** [comment]
Ok thanks. I have opened a new issue to track the progress: https://github.com/MobileChromeApps/mobile-chrome-apps/issues/532

**Comment by felixhammerl** [comment]
this is a monthly ping to @agrieve and @oahziur about this issue, given that it is now 7 months old ...
