### ISSUE TITLE
Background scripts should run in an android service

### ISSUE THREAD

**Issue by MehSha** [MobileChromeApps/mobile-chrome-apps#322]
Hi, i have written my background page so that if it receive an SIP INVITE and the main window is closed. it reopens it and make it receive the call. it works on windows (in manifest persistent:true is included). but in my android app when i close the app (hold home and swipe away the app thumnail) it will not get reopened again.
i first thought you have implemented the background (or persistent backgrouns) like a service which may create any window even if the app is closed. but inspecting the android app manager i found there is no such a service.
is it a bug or by design, will it get implemented?

**Comment by longsleep** [comment]
I am facing a similar issue here. I have an app which does have a Websocket connection which needs to be kept open to receive incoming messages when in the background (or at least it needs to restart the connection as soon as possibl when in the background).

My use case is that the app can keep a continuous Websocket connection to a remote server and be able to respond (like with a notification) if some data comes in.

**Comment by luisreyes** [comment]
I need to setup chrome alarms when the device turns on without having to open the app. My application would be kind of pointless without this. I started rewriting the app in native since this doesn't seem to be ready. Any updates?

**Comment by agrieve** [comment]
This is now launched with cca@0.7.0
