### ISSUE TITLE
Document how to add platform-specific icons

### ISSUE THREAD

**Issue by agrieve** [MobileChromeApps/mobile-chrome-apps#404]
And verify that it does actually work :P.

Using manifest.mobile.json's platform keys you can have platform-specific "icon" manifest values.

Should update icon docs here: https://github.com/MobileChromeApps/mobile-chrome-apps/blob/master/docs/NextSteps.md

**Comment by felquis** [comment]
> And verify that it does actually work :P.

This was working so so in 0.5.0 but in 0.5.1 this isn't working.

* For android, the icons in `manifest.mobile.json` are ignored and the icon used for Android is the one in `manifest.json`, for iOS seems to be working fine!
* Splash Screens was working on 0.5.0 but isn't working on 0.5.1, I'm debugging trying to figure out what's wrong but with no success, any tips?
