### ISSUE TITLE
Cordova Camera plugin not importing?

### ISSUE THREAD

**Issue by Ledda** [MobileChromeApps/mobile-chrome-apps#417]
I cant get the Cordova Camera plugin to load and I keep getting:

Uncaught TypeError: Cannot read property 'getPicture' of undefined 

I have installed the plugin via CLI and it successfully installed into my local directory, because I can see it there with all the .js files.

cordova plugin add org.apache.cordova.camera

I am confident I have not violated the standards for the options allowed for a tablet. Did I miss a solution somewhere? Ive been searching and trying to fix for days now.

>navigator.camera.getPicture(function(imageURI) {
        console.log(imageURI);
    }, function(err) {
        alert('Failed because: ' + err);
    }, {
        quality : 75,
        destinationType : Camera.DestinationType.DATA_URL,
        sourceType : Camera.PictureSourceType.CAMERA,
        encodingType: Camera.EncodingType.JPEG
    });

http://docs.phonegap.com/en/3.3.0/cordova_camera_camera.md.html#Camera

(Samsung GALAXY Note 8.0 - Android Version 4.2.2)
(CADT - 0.9.0)
(cca v0.4.3)

**Comment by agrieve** [comment]
Ah, glad you figured it out! This is definitely a bad bug, and one we'll be looking to address in the near future. It's filed also at:
MobileChromeApps/chrome-app-developer-tool#31
