### ISSUE TITLE
org.chromium.iossocketscommon not working with appgyver build service

### ISSUE THREAD

**Issue by gurkerl83** [MobileChromeApps/mobile-chrome-apps#419]
Hi,
we are trying to get chrome.sockets.udp api working with Appgyver`s build service. Inserting this plugin as a dependency we are getting the following error. This happens on iOS builds only. 

Adding {“source”:“org.chromium.iossocketscommon”} which is required by chrome.sockets.upd via <dependency id=“org.chromium.iossocketscommon” /> is the reason for the build error on iOS.
The build error log mentions the following
ld: 66 duplicate symbols for architecture armv7
pastebin.com/138Uz4gH
The build services resolves all dependencies for android – build successful.

Running the app via cca command line tool + inserting sockets permissions in the manifest.json file works for both iOS and Android!

"sockets": {
    "udp": {
      "bind": "*",
      "send": "*",
      "multicastMembership": ""
    },
}

Thanks!

**Comment by jpchase** [comment]
We don't have any concrete changes planned to address this, so closing for now.
