### ISSUE TITLE
Doesn't use the latest version of Crosswalk

### ISSUE THREAD

**Issue by BrianGeppert** [MobileChromeApps/mobile-chrome-apps#465]
The bug is actually [here](https://github.com/MobileChromeApps/cordova-crosswalk-engine/blob/master/fetch_libs.sh#L1-L2), but that project doesn't have an issue tracker.

**Comment by baleboy** [comment]
I just installed cca and it seems to be using Crosswalk 8. I would like to try out the latest Crosswalk, are there any instructions on how to do it?

**Comment by mmocny** [comment]
The version of crosswalk we bundle is based on the [cordova-crosswalk-engine submodule here](https://github.com/MobileChromeApps/mobile-chrome-apps/tree/master/cordova).

The latest version on master of cca is actually version 11 (beta), but we haven't released `cca` in a while.

If you would like to try it right now, you can follow our instructions for [cloning-this-repo](https://github.com/MobileChromeApps/mobile-chrome-apps/blob/master/dev-docs/cloning-this-repo.md).

Either way, we should probably see about updating crosswalk again and doing a `cca` release.  Thanks for the reminder.

**Comment by baleboy** [comment]
Thanks for the reply. I assume the same applies to CADT, i.e. if I follow the instructions below will I get a CADT based on Crosswalk 11?

https://github.com/MobileChromeApps/chrome-app-developer-tool/#building-from-source-ios-or-android---instructions-for-ios--linux

**Comment by mmocny** [comment]
That isn't necessarily true. CADT isn't built with cca. However it's using
the same crosswalk engine plugin, so it may just need a submodule update if
anything. I'll check soon.

**Comment by mmocny** [comment]
..okay you are right, CADT build script uses the version of `cordova-crosswalk-engine` which is bundled with `cca`.  So long as you `npm link` the master version of `cca` into your CADT directory before building, you will get the latest.

We have scheduled a `cca` release for later this week, which I think @jpchase and @agrieve are going to do.

**Comment by jesusprubio** [comment]
"RTCPeerConnection" (needed for WebRTC) problem also related with not to be using the last Crosswalk version. The generated SDP is not compatible with the one provided by the actual Chrome stable. I've tested the same code with the last Xwalk (Cordova version) and the problem disappeared.

Any date for the new version? :)
Thanks

**Comment by agrieve** [comment]
Long overdue, I know!
Just published a release candidate that includes newer crosswalk. Would be great if you wanted to try it out!

    npm install -g cca@0.6.0-rc1

**Comment by jesusprubio** [comment]
I think this issue can be closed since the publication of the last release (v0.6.0), for me is working now. :)
