### ISSUE TITLE
question: What about splash screens on Android?

### ISSUE THREAD

**Issue by AleksMeshkov** [MobileChromeApps/mobile-chrome-apps#466]
[Here] (https://developer.chrome.com/apps/chrome_apps_on_mobile#splash-screens) is described how to deal with splash screens on iOS. What about Android?

Thanks!

**Comment by felquis** [comment]
With CCA@0.5.1 it doesn't work anymore, I'll check out the issues worked in this version to see what was changed.

**Comment by sunbiz** [comment]
I found a solution to the problem. I manually built the latest from https://github.com/apache/cordova-plugin-splashscreen and used it with cca. And then it works fine with CCA 0.5.1

**Comment by felquis** [comment]
@sunbiz it works :) Thank you!

**Comment by jpchase** [comment]
It seems that using the latest version of the cordova splashscreen plugin will address everyone's needs.  There was a cordova plugin release in February, so the updated plugin should be widely available.
