### ISSUE TITLE
Background Service with CCA

### ISSUE THREAD

**Issue by GustavoCostaW** [MobileChromeApps/mobile-chrome-apps#475]
Hello guys, I want to create a background service with CCA, is there any plugin that can help me with this? I want to check the user's SMS when it receives an SMS even if the application is closed, only for Android, iOS that Apple does not allow, someone has some way so that I can do this? grateful.

**Comment by jpchase** [comment]
If interested in our efforts on improving background functionality, see #322.  Otherwise, we'll leave it to you to pursue writing a custom Cordova plugin.
