### ISSUE TITLE
cca upgrade fails with "cannot install org.chromium.storage" without storage permission

### ISSUE THREAD

**Issue by mmocny** [MobileChromeApps/mobile-chrome-apps#476]
I thought I made it work with plugins that are forced to install, but its failing for Glenn

**Comment by jpchase** [comment]
I am unable to reproduce this with the latest cca (0.6.0-rc1).  I created a new app, add the "notifications" permission only, then ran upgrade.  All the required/dependent plugins were installed without issue.
