### ISSUE TITLE
Adding "permissions": ["gcm"] and then removing it causes app to no longer make XHRs

### ISSUE THREAD

**Issue by wesleycho** [MobileChromeApps/mobile-chrome-apps#488]
I did
<pre>
"permissions": [
  "&lt;all_urls&gt;", "gcm"
]
</pre>
in the manifest.json while experimenting with something, and when I run the build, I can no longer make XHRs via XmlHttpRequest - this has something to do with org.chromium.gcm being added and then removed, unintentionally blowing away something else critical or causing it to fail.

**Comment by agrieve** [comment]
Awesome! I see now that the problem is that the INTERNET permission was being removed. Pushed a work-around for it, and filed a Cordova bug for it: https://issues.apache.org/jira/browse/CB-8236
