### ISSUE TITLE
question: How to get newer crosswalk version (chromium 39) in cca?

### ISSUE THREAD

**Issue by scmsystm** [MobileChromeApps/mobile-chrome-apps#490]
Hi, I'm trying updating crosswalk WebView with newer version to get chromium 39 on `cca 0.5.1` android apps by updating `cordova-crosswalk-engine` to  latest master branch commit [1f7883d] (https://github.com/MobileChromeApps/cordova-crosswalk-engine/commit/1f7883dbfe0f5cfb3258e358b123129be8597b91) and manually change files in `cordova-lib` with this  [this](https://git-wip-us.apache.org/repos/asf?p=cordova-lib.git;a=commitdiff;h=02a96d75).
It's buildable, but the app crashed at launch.
Here's the console log:
[adb logcat](http://pastebin.com/wJH7XbdQ)
[tombstone](http://pastebin.com/QXWe0iFW)

crosswalk stable and beta version in this [repository](https://download.01.org/crosswalk/releases/crosswalk/android/maven2/org/xwalk/) was tested, all version resulting app crashed at launch.

I'm also trying to build without chromium plugins that listed in `cca/node_modules/cca-manifest-logic/src/plugin-maps.js` and pointing app content directly to index.html.

The result, app was launched successfully, but should I use cca without plugins?
Is possible one of chromium plugin that make crosswalk crash?

Btw, I wanted chromium 39, because Polymer paper-input is require double tap to show soft-keyboard in chromium < 39.
Polymer paper-input are working normal in chromium 39 (tested in latest Chrome android).

Thank you.

**Comment by schme16** [comment]
Further to this, replacing: 
org.chromium.boostrap/api/mobile.js:80 with:
```  
bgWnd.history.replaceState(null, null, ('file:///android_asset/www/index.html'));
```

Let my app start up correctly, including all plugins and Google Play service api calls, such as identity and in app purchases (payments), which rocks because now I can use the [BeaconAPI](http://updates.html5rocks.com/2014/10/Send-beacon-data-in-Chrome-39) that's only available in Chome beta builds >39!

**Comment by longsleep** [comment]
I can confirm that ploymer paper-input require two taps to make the soft-keyboard show with the currently released cordova-crosswalk-engine getting installed with cca. Also the steps provided above do seem to fix support to install the latest head of cordova-crosswalk-engine. Though the change to mobile.js does have side effects - though without it the app crashes. 

So - what are the plans to upgrade to latest crosswalk engine with Chromium 39 and later so the cca apps can use the very latest of the features. Manually upgrading this seems scary and the resulting app does have various issues.

**Comment by mmocny** [comment]
@clelland fyi.

**Comment by clelland** [comment]
I've created https://crosswalk-project.org/jira/browse/XWALK-3344 to track this on the Crosswalk-project side.

**Comment by schme16** [comment]
Another temp. solution is to create a file named `xwalk-command-line` in your `platforms/android/assets` folder and set the content of the file to: `xwalk --disable-web-security`.
As the flag suggests, it does turn off all the CORS features, so be sure use it with caution...

**Comment by jpchase** [comment]
cca is now using Crosswalk 11 (Chromium 40), and the crash problem (XWALK-3344) has been resolved.

@clelland anything left to do on this issue?

**Comment by clelland** [comment]
The issue was really more about history.replaceState('chrome-extension://....') working, rather than Chromium 39+ -- The only thing left to do is to see if that method still crashes a cca app.

**Comment by jpchase** [comment]
The replaceState method is working for chrome-extension urls in a cca app.
