### ISSUE TITLE
OpenSSL Version Error

### ISSUE THREAD

**Issue by bannostookaylo** [MobileChromeApps/mobile-chrome-apps#492]
I packaged my apk file and uploaded it but the google play store is saying this

"Security alert
Your app is statically linking against a version of OpenSSL that has multiple security vulnerabilities. You should update OpenSSL as soon as possible. Please see the alerts page for more information."

**Comment by felixhammerl** [comment]
we've also experienced this. it's an issue with the crosswalk webview using outdated openssl version :+1:

**Comment by mmocny** [comment]
@felixhammerl Did you resolve this manually / file an issue with them?

@clelland fyi.

**Comment by jpchase** [comment]
We've updated to Crosswalk 11, which addresses the problem.  This will be included in the next release of cca (coming soon!).

Until that release, see [XWALK-3217](https://crosswalk-project.org/jira/browse/XWALK-3217) for possible workarounds.

**Comment by jonobr1** [comment]
Just to clarify, does cca v0.5.1 address this problem or do we need to still use the workaround for this?
