### ISSUE TITLE
compiling for Android fails if there are spaces in the project path

### ISSUE THREAD

**Issue by fenwick67** [MobileChromeApps/mobile-chrome-apps#496]
(Windows x64)

running `cca compile android` (and of course `cca build android` or `cca run android`) from `C:\Users\Drew\desktop\app projects\myapp` produces the following error (using cca v0.5.1):

```
cca v0.5.1
Running command: cmd "/s /c ""C:\Users\Drew\desktop\app projects\myapp\platforms\android\cordova\bui
ld.bat"""
'C:\Users\Drew\Desktop\app' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Drew\Desktop\app projects\myapp\platforms\android\cordova\node_modules\q\q.js:126
                    throw e;
                          ^
Error code 1 for command: cmd with args: /s,/c,C:\Users\Drew\Desktop\app projects\myapp\platforms\an
droid\gradlew,assembleDebug,-b,C:\Users\Drew\Desktop\app projects\myapp\platforms\android\build.grad
le,-Dorg.gradle.daemon=true,-x,lint,-x,lintVitalRelease,-x,compileLint,-x,copyReleaseLint,-x,copyDebugLint
Error: cmd: Command failed with exit code 8
    at ChildProcess.whenDone (C:\Users\Drew\AppData\Roaming\npm\node_modules\cca\node_modules\cordova\node_modules\co
rdova-lib\src\cordova\superspawn.js:135:23)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Process.ChildProcess._handle.onexit (child_process.js:823:5)>
```

Moving the project to c:\Users\Drew\desktop\myapp causes it to run successfully.

This is easily reproduced by going into any directory with a space in it and...
```
>cca create myapp
>cd myapp
>cca build android
```

**Comment by mmocny** [comment]
Error message implies the problem lays in superspawn (in cordova-lib).  Oddly, looks like superspawn was written specifically to work in this case, but there must be a bug.

**Comment by mmocny** [comment]
I don't have a windows machine/vm at the moment, so I won't take a stab at this right now.  If no one else picks it up I'll take a stab next week hopefully.

**Comment by agrieve** [comment]
Looks like this is an upstream bug and was just fixed in cordova-android via apache/cordova-android@8e5c93a31. Fix will make it into the next cca release
