### ISSUE TITLE
iPhone 6/6+ auto scaling

### ISSUE THREAD

**Issue by felixhammerl** [MobileChromeApps/mobile-chrome-apps#501]
Hi guys,

our cca-built app is currently auto scaling from iPhone 5 resolution to iPhone 6 and 6+. Are you aware of this and are you planning to address this? How can I help in the process? Do you know of any reliable workaround in the meantime?

Cheers
Felix

**Comment by mmocny** [comment]
I believe this issue was fixed in cordova-ios 4.0, and we're still pinned to 3.7.0.

If you are using cca master, you can update the `cordova/cordova-ios` submodule to 4.0.0.  I'm doing that now to confirm.

**Comment by mmocny** [comment]
My bad, 4.0 was the versions of cordova-cli that included cordova-ios 3.7.0.

The iOS8 tracking issue is [CB-7043](https://issues.apache.org/jira/browse/CB-7043).

I found a forum thread about this issue which may have some insights: http://forum.ionicframework.com/t/ios8-iphone-6-app-is-being-scaled-up-instead-of-native/10957/8

**Comment by jpchase** [comment]
We just published a release candidate that includes cordova-ios 3.8.0.  According to the forum thread, it seems that an upgrade could address the scaling issue.  Would be great if you wanted to try it out!

    npm install -g cca@0.6.0-rc1

We'll assume that fixes the scaling, but feel free to re-open this issue if there's still a problem.
