### ISSUE TITLE
Problem while trying to run/build application

### ISSUE THREAD

**Issue by VictorQueiroz** [MobileChromeApps/mobile-chrome-apps#503]
![captura de tela - 10-01-2015 - 00 10 33](https://cloud.githubusercontent.com/assets/5693176/5690271/347c8458-985d-11e4-9c65-b1c68fe3e656.png)

Why I keep having this error while trying to run my application which I just created with
```
cca create MyApp
```

Someone can help me?

**Comment by VictorQueiroz** [comment]
I just uninstalled everything about JDK on my OS and installed Java 8.

```
sudo apt-get purge -y openjdk*
sudo apt-get install -y openjdk-8-jre openjdk-8-jdk
```

It did the job, thank's!

**Comment by mmocny** [comment]
Thanks for checking back in!
