### ISSUE TITLE
Bluetooth and socket plugins don't compile on cordova 3.x

### ISSUE THREAD

**Issue by agrieve** [MobileChromeApps/mobile-chrome-apps#506]
As reported: 
http://stackoverflow.com/questions/27085944/cordova-with-chrome-tcpserver-plugin-wont-compile-getpluginmanager

**Comment by mmocny** [comment]
Are you going to answer the SO question, or would you like me to?

**Comment by agrieve** [comment]
Was going to wait until we're able to publish the fix to answer.
