### ISSUE TITLE
google play services 22.0.0 return 404

### ISSUE THREAD

**Issue by felixhammerl** [MobileChromeApps/mobile-chrome-apps#508]
hi guys, it's currently not possible to build using google play services v22.0.0, because it returns a 404...

> wget http://registry.cordova.io/com.google.playservices/-/com.google.playservices-22.0.0.tgz
--2015-01-14 14:13:43--  http://registry.cordova.io/com.google.playservices/-/com.google.playservices-22.0.0.tgz
Resolving registry.cordova.io... 50.17.177.14
Connecting to registry.cordova.io|50.17.177.14|:80... connected.
HTTP request sent, awaiting response... 404 Object Not Found
2015-01-14 14:13:44 ERROR 404: Object Not Found.

**Comment by mmocny** [comment]
I just ran into this as well.

By installing the plugin manually from [here](https://github.com/MobileChromeApps/google-play-services) resolved the issue for me.  Andrew tried to publish this plugin (and others?) to the plugin registry a few days ago and it failed.  Seems it actually half-updated and may be in a broken state.  We will look into republishing asap.

**Comment by agrieve** [comment]
Seems the plugin registry is having issues :( 

https://issues.apache.org/jira/browse/CB-8284

I've reverted the broken release, so should be good again.

**Comment by felixhammerl** [comment]
can confirm:
```
npm http GET http://registry.cordova.io/com.google.playservices
npm http 200 http://registry.cordova.io/com.google.playservices
```

thanks!
