### ISSUE TITLE
bootstrap fails because of foreground page html comments

### ISSUE THREAD

**Issue by mmocny** [MobileChromeApps/mobile-chrome-apps#510]
As reported in #402.

..likely due to parsing failure.

We've previously had a similar issue with comments causing a startup error when their was a `<head>` tag in a comment before the actual `<head>`.  This is because our [runtime bootstrap code](https://github.com/MobileChromeApps/mobile-chrome-apps/blob/master/chrome-cordova/plugins/chrome-bootstrap/api/app/window.js#L151) re-writes the content of your foreground window.

**Comment by mmocny** [comment]
@FreakTheMighty If you don't mind digging just a bit further, I would debug and step through that [`rewritePage`](https://github.com/MobileChromeApps/mobile-chrome-apps/blob/master/chrome-cordova/plugins/chrome-bootstrap/api/app/window.js#L151) function and see where it chokes.  If you can't get to it, I'll take a look soon.

**Comment by agrieve** [comment]
I've got a fix in progress

**Comment by agrieve** [comment]
(it's exactly what you said)

**Comment by mmocny** [comment]
Huzzah!
