### ISSUE TITLE
Problems using Google Maps on mobile-chrome-apps CCA

### ISSUE THREAD

**Issue by dolce** [MobileChromeApps/mobile-chrome-apps#513]
Hello guys, I'm currently trying to create a project with mobile-chrome-apps using the Google Maps, however when I try to use the plugin.google.maps appears some errors in java compilation. And if I try to use without the GoogleMaps plugin, only including the scripts of API, does not occur errors but the map its not displayed.

This is strange, because if I compile without the CCA, only with the cordova, the GoogleMaps functions work normally.
Does anyone know a solution?

**Comment by agrieve** [comment]
Looks like the maps plugin isn't compatible with the tip-of-tree version of cordova-android that we're using in CCA. Good news is that cordova-android@4.0.0 is nearing launch readiness.
