### ISSUE TITLE
pluginInitialize method does not override or implement method from supertype

### ISSUE THREAD

**Issue by copleykj** [MobileChromeApps/mobile-chrome-apps#515]
I'm trying to use the Cordova notifications plugin within a MeteorJs Cordova integration. When meteor tries to build the notifications plugin I get the error below. Not sure of the reason for this error since the CordovaPlugin class clearly has a pluginInitialize method. Any pointers as to what the cause of this error would be greatly appreciated.

```
[javac]  ChromeNotifications.java:80: error: method does not override or implement a method from a supertype
[javac]  @Override
```

**Comment by agrieve** [comment]
Likely the case is that the version of cordova-android that you're using is too old.

**Comment by jpchase** [comment]
Given that we're not seeing this problem, the assumption is the solution is updating your version of cordova-android, as agrieve suggested.  As result, this issue will be closed.

If that doesn't resolve your error, please re-open the issue with additional details (including your cordova-android version).
