### ISSUE TITLE
Not combatible with Telerik's WkWebView plugin

### ISSUE THREAD

**Issue by BrianGeppert** [MobileChromeApps/mobile-chrome-apps#516]
[Telerik has a WkWebView plugin](https://github.com/Telerik-Verified-Plugins/WKWebView) that emulates UIWebView and enables a number of Cordova plugins to work (by exposing a limited UIWebView-like wrapper).  I've not been able to get a clean crash, though, so I haven't been able to identify what exactly is wrong.

**Comment by BrianGeppert** [comment]
Is it possible to use the google.payments polyfill without the Mobile Chrome Apps wrapper?  I'd like to do that until I'm able to work out exactly where the incompatibility is between Mobile Chrome Apps and the WkWebView plugin.

**Comment by agrieve** [comment]
Absolutely! Just "cordova plugin add" it :)

**Comment by BrianGeppert** [comment]
Thanks!
