### ISSUE TITLE
Recurring/subscription purchases don't appear to be supported

### ISSUE THREAD

**Issue by BrianGeppert** [MobileChromeApps/mobile-chrome-apps#517]
Would this be a good bug for someone new to the project?

**Comment by jpchase** [comment]
I'm assuming you're referring to adding support to the google.payments plugin.

The generic answer is we're always happy to receive pull requests to fix/enhance the functionality of Chrome Apps for Mobile :-).

More specifically, we haven't done much investigation into recurring/subscription purchases.  So, this issue could be straight-forward to implement, and thus a good place to start.  On the other hand, it could be infeasible or difficult to implement.  It would also depend on your familiarity with mobile payments in general.

If you're still looking to get your feet wet with Chrome Apps for Mobile, I'd guess there are easier places to start.  You could review other issues in this repository, or look at our [API Status](github.com/MobileChromeApps/mobile-chrome-apps/blob/master/docs/APIsAndLibraries.md) for gaps in functionality.
