### ISSUE TITLE
MCA broke touch events in my Polymer.Dart app

### ISSUE THREAD

**Issue by BrianGeppert** [MobileChromeApps/mobile-chrome-apps#518]
Or maybe the other way around?  I have an app that I wrote, and touch events worked fine up until I converted it to be a Mobile Chrome App.  I'm not getting any error messages.  Mouse events still work on desktop, but touch events don't work on iOS (I don't have a touchscreen on my PC, and haven't yet tested it on Android).  I can share the code privately if anyone thinks this is worth looking into.

**Comment by jpchase** [comment]
As in #451, we really haven't done much with Polymer.Dart.  For Polymer in general, we have been able to get it to work on iOS.  However, we haven't tested on iOS recently, and it's very dependent on the frequent changes in Polymer.

I'd suggest we'd need a lot more details before we'd be able to help, including the code, build instructions, test results on Android, .etc.

We'll close/backlog this issue for now, on the assumption you've found a solution/workaround.  Feel free to re-open if assistance is still needed.
