### ISSUE TITLE
Master branch broken?

### ISSUE THREAD

**Issue by schme16** [MobileChromeApps/mobile-chrome-apps#524]
I've tried installing from the master branch (id'd as 0.5.2-dev at the time of writing this) and from the normal stable (0.5.1), and  while it will install just fine and even creates projects OK, when I do a first run (not having changed the new projects files at all) it fails with: `Error: 404 Not Found: org.apache.cordova.engine.crosswalk`.

After some digging, it seems this is because the repo for crosswalk has been renamed (to org.crosswalk.engine), with the cordova registry entry removed(?); and due to the `org.apache.cordova.engine.crosswalk` plugin getting marked as deprecated (in: [cca-manifest-logic/src/plugin-map.js](https://github.com/MobileChromeApps/mobile-chrome-apps/blob/master/cca-manifest-logic/src/plugin-maps.js#L51)), it has removed all the current versions of my crosswalk files and cannot find the new ones to add.

It's been like this nearly the whole month, any ETA on when this will get sorted out? (for now I can manually fix things, but its a pain)

**Comment by agrieve** [comment]
Yeah, it's in an annoying state right now in that it depends on an
unreleased version of cordova-lib. Should work out if you npm link the
master version of cordova-lib and cordova-cli. Also don't forget to npm
link the cca-manifest-logic module that exists within the repo.

**Comment by schme16** [comment]
Thanks for the heads up @agrieve, I npm linked to the latset head of each oth the libs you mentioned , and sure enough it worked. I assume this will all be sorted out in 0.5.2 (?)

**Comment by agrieve** [comment]
Great! Yes. It will.

**Comment by agrieve** [comment]
FYI - this is now resolved, and there's a release-candidate for the next version of cca:

    npm install -g cca@0.6.0-rc1
