### ISSUE TITLE
Blank screen when app brought to foreground after started from alarm/gcm event

### ISSUE THREAD

**Issue by apaulus** [MobileChromeApps/mobile-chrome-apps#525]
Hi,
Could someone please have a look at https://github.com/MobileChromeApps/mobile-chrome-apps/issues/297 ?
This is still happening to me: I register for GCM, kill the app, send a GCM message from the server and the D/XWalkCordovaWebViewClient﹕ onPageFinished(file:///android_asset/www/plugins/org.chromium.bootstrap/chromeapp.html) gets launched without processing my code (showing a black background screen when I bring the app into the foreground).
My cca version is 0.5.1. The org.chromium.bootstrap plugin is 1.1.3 (Jan 28, 2015) according to README.md. Btw, in the "Release Notes" section there is no mention of #297 being fixed.
Users currently need to kill the app every time a GCM message was received while the app was not running :/

**Comment by jpchase** [comment]
We've been working on improving the background functionality (see #322).  That work includes addressing the behaviour of background events when the app is not running.

The effort was delayed for a while, but we're back in active development.  The goal is to complete the work in the next few weeks.

**Comment by apaulus** [comment]
Sounds great! Keep up the good work :)

**Comment by jpchase** [comment]
This problem has been fixed, and is available in the latest cca release candidate (just out today).
