### ISSUE TITLE
navigator.vibrate() Doesn't work on Android

### ISSUE THREAD

**Issue by stevenlaidlaw** [MobileChromeApps/mobile-chrome-apps#526]
Only tested on Android 5.0.1

Javascript's native vibrate function doesn't translate over the device when converted to an app.

**Comment by jpchase** [comment]
I did a quick test, and I'm guessing your app needs to request the Android "vibrate" permission.

There are a few options:
- Manually request the permission, by editing the AndroidManifest.xml, under the platforms/android directory.
- Write a plugin, whose only job is to provide the configuration to add the permission to the manifest
- Use the existing cordova plugin that already implements vibration.  Just `plugin add org.apache.cordova.vibration`.  For details, see https://github.com/apache/cordova-plugin-vibration

I would recommend the last option, as it's supported and lets you use the same `navigator.vibrate` API.
