### ISSUE TITLE
cannot compile due to incorrect version of android cordova plugin

### ISSUE THREAD

**Issue by eesdil** [MobileChromeApps/mobile-chrome-apps#529]
using the command 'cca build' fails at compiling compileArmv7DebugJava, because we are missing two functions inCordovaPlugin.java to override:
- shouldAllowNavigation
- shouldAllowRequest

after returning just null instead of calling the supers it compiles fine
cca version: v0.5.1
osx: 10.10.2 Yosemite

**Comment by agrieve** [comment]
Thanks for bringing this to our attention! I've made the fix that you suggested. 0638d3370c29d47ac5396c36067b2307a97dd9d2
