### ISSUE TITLE
Broken setup on Wercker CI/CD server

### ISSUE THREAD

**Issue by marcellodesales** [MobileChromeApps/mobile-chrome-apps#537]
While trying to create a CI/CD box on Wercker http://old-devcenter.wercker.com/articles/boxes/bash.html, I couldn't start using `cca`. The problem is that the analytics is read only from a file... 

https://github.com/MobileChromeApps/mobile-chrome-apps/blob/8821dcb47ccc0188c8dc6301aa88544da6b44f9f/src/analytics-loader.js#L63

Could you create a switch to automatically accept for CI/CD environments?

I got it installed:

```
cca@0.6.0 /usr/lib/node_modules/cca
├── cca-manifest-logic@1.0.0
├── xmldom@0.1.19
├── node-uuid@1.4.3
├── q@1.2.0
├── underscore@1.8.2
├── debounce@1.0.0 (date-now@1.0.1)
├── node.extend@1.1.3 (is@2.1.0)
├── semver@4.3.3
├── shelljs@0.4.0
├── optimist@0.6.1 (wordwrap@0.0.2, minimist@0.0.10)
├── crypto-js@3.1.2-5
├── elementtree@0.1.6 (sax@0.3.5)
├── gaze@0.5.1 (globule@0.1.0)
├── gulp-mocha@1.1.2 (through@2.3.6, gulp-util@3.0.4, mocha@1.21.5)
├── update-notifier@0.3.1 (semver-diff@2.0.0, is-npm@1.0.0, string-length@1.0.0, chalk@1.0.0, latest-version@1.0.0, configstore@0.3.2)
├── chrome-app-developer-tool-client@0.0.5 (agentkeepalive@1.2.1, old-agentkeepalive@0.2.2, q@0.9.7, temp@0.7.0, shelljs@0.1.4, adbkit@2.1.6, jszip@2.1.1)
└── cordova@4.3.0 (underscore@1.7.0, q@1.0.1, nopt@3.0.1, cordova-lib@4.3.0)
```

After the creation of the box, I try to print the version of cca and it requests the confirmation of the analytics question, which breaks the build.

![screen shot 2015-03-30 at 2 40 29 pm](https://cloud.githubusercontent.com/assets/131457/6907417/d01dbfbe-d6ea-11e4-9e1a-b197de8db1cf.png)

Is there an optional way to setup cca without the analytics question? Or should I manipulate the file before running it the first time?

thanks!

**Comment by mwoghiren** [comment]
Hi there,

The quickest way would be to update (or create) the config file at `~/.cca/config`, adding the following:

```
{
    "analytics": {
        "isAllowed": false,
    }
}
```

That should do it.

Alternatively, you could update the file you linked to `return Q(false);` on line 59 in the file you linked, `analytics-loader.js`.

I think either should work.  Let us know if you're still running into problems.  Thanks!

**Comment by kamrik** [comment]
You can also run `cca analytics disable` as the first command after installing cca. This will create the `~/.cca/config` file Max mentioned.

**Comment by marcellodesales** [comment]
@kamrik that's exactly what I was looking for!

**Comment by mwoghiren** [comment]
Hah, good call. Forgot about that.

**Comment by marcellodesales** [comment]
Perfect... The wercker build is showing the following:

```
$ cca analytics disable
Usage statistics collection disabled.
$ cca --version
0.6.0
```

I still cannot build a box in Wercker though :( It's a shared attempt to help people build and deploy CCA apps. The Ubuntu 12.04 server I'm trying to use gets more than the limit of 1500MB  https://app.wercker.com/#applications/551b2cbbbb95a8811902f250

```
Versions
$ 
$ node --version
v0.10.37
$ npm --version
1.4.28
$ java -version
java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b25)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)
$ ant -version
Apache Ant(TM) version 1.8.2 compiled on December 3 2011
$ grunt --version
grunt-cli v0.1.13
$ bower --version
1.4.0
$ cca analytics disable
Usage statistics collection disabled.
$ cca --version
0.6.0
$ 
```

**Comment by kamrik** [comment]
One option I would try is to go without building your own box, use the stock Android box they provide and have you app list cca as one of its' npm deps.

I experimented with Gulp based workflow for cca apps where cca is an npm dependency of the app here: https://github.com/kamrik/GulpCCA
This is somewhat half baked, though.
