### ISSUE TITLE
Accessing Native Client from Cordova.

### ISSUE THREAD

**Issue by topless** [MobileChromeApps/mobile-chrome-apps#539]
This is more of a cry for guidance than an issue. 
We have a chrome app that works on all desktop OS, and then we wrap it with `cca` according to your instructions and works for Android nicely.
We added a `.cpp` library to our chrome app with the help of `Native Client` and it works for desktops. We tried the same process with `cca` and the app is not loading which makes perfect sense. How can I achieved the desired effect?
We are thinking of writing a Cordova plugin that will load the `c++` library with `JNI` and will do the mapping from `JavaScript` to `c++`, but I was wondering if there is another way, so we can keep it consistent and both apps use the native client approach but with different arch builds for the library for example.

**Comment by agrieve** [comment]
JNI is the answer afaik.

**Comment by topless** [comment]
I have posted a more specific [question](http://stackoverflow.com/questions/29533271/include-native-libraries-with-mobile-chrome-app) on SO, as I didn't consider it an issue in first place.
