### ISSUE TITLE
"--skip-prompt" switch is not working when installing plugins

### ISSUE THREAD

**Issue by marcellodesales** [MobileChromeApps/mobile-chrome-apps#540]
Shouldn't "--skip-prompt" work to accept the update? as documented in the cca --help :( I was forced to use "--skip-upgrade", which works as discussed on #453. 

```
Options:
  -h, --help         Show usage message.                  
  -d, --verbose      Enable verbose logging.              
  -v, --version      Show version.                        
  -y, --skip-prompt  Answer "yes" to any "yes/no" prompts.
  --skip-upgrade     Don't upgrade platforms and plugins. 
```

When I try to use the skip command it fails:

```
$ cca --skip-prompt plugin add org.apache.cordova.device
cca v0.6.0
This project was not upgraded to cca v0.6.0 yet.  Attempting to upgrade now...
Warning: Upgrade will replace all files in platforms and plugins. Continue? [y/N] 

$ cca plugin --skip-prompt add org.apache.cordova.device
cca v0.6.0
This project was not upgraded to cca v0.6.0 yet.  Attempting to upgrade now...
Warning: Upgrade will replace all files in platforms and plugins. Continue? [y/N] 

$ cca plugin add --skip-prompt org.apache.cordova.device
cca v0.6.0
This project was not upgraded to cca v0.6.0 yet.  Attempting to upgrade now...
Warning: Upgrade will replace all files in platforms and plugins. Continue? [y/N] 

$ cca plugin add org.apache.cordova.device --skip-prompt
cca v0.6.0
This project was not upgraded to cca v0.6.0 yet.  Attempting to upgrade now...
Warning: Upgrade will replace all files in platforms and plugins. Continue? [y/N] 
```

Anything I'm missing?

Thanks!
Marcello

**Comment by mmocny** [comment]
Confirmed `-y` and `--skip-prompt` do not work.

**Comment by mmocny** [comment]
Seems this only ever worked for the `cca upgrade` command.  Seems silly and inverted actually.. if you explicitly call `cca upgrade` you should never get the prompt, and the --skip should apply only to other commands.  I'll see about making the change.

**Comment by marcellodesales** [comment]
@mmocny Thanks for fixing this! I will try it!

**Comment by marcellodesales** [comment]
When will this be released?

**Comment by mmocny** [comment]
During the next cca release.  I don't think this is major enough to push for a quick release, but I'll ask around to see if there are other reasons..

**Comment by mmocny** [comment]
..We'll be doing releases quite a bit over the coming weeks (with cordova-android 4.0 moving to official release, with various cordova-lib tooling changes, and several cca plugin updates coming).

So, I recommend waiting 1-2 weeks.

**Comment by mmocny** [comment]
Or follow our [cloning](https://github.com/MobileChromeApps/mobile-chrome-apps/blob/master/dev-docs/cloning-this-repo.md) docs if you are impatient!

**Comment by marcellodesales** [comment]
@mmocny so far so good :+1:
