### ISSUE TITLE
Latest update v0.6.0 breaks project (Content-Security-Policy) using Polymer

### ISSUE THREAD

**Issue by shanling** [MobileChromeApps/mobile-chrome-apps#544]
I need to use inline scripts with Google Polymer and it appears that the new update has made it so that Content-Security-Policy is enabled by default. The documentation says this:

"Content-Security-Policy now works and enabled by default (can be disabled though)"

How do I disable it? I can't find it listed anywhere. Thanks.

**Comment by ragingwind** [comment]
If you would like to use vulcanize(with gulp) on developing with cca. Take look this: https://github.com/ragingwind/mobile-chrome-apps-starter-kit

**Comment by shanling** [comment]
I'll give Vulcanize a try, thanks.

**Comment by agrieve** [comment]
So you know - The CSP values options are documented here:
https://github.com/MobileChromeApps/mobile-chrome-apps/blob/master/docs/NextSteps.md

so, you'd use `"cspUnsafeEval":"true"` in `your manifest.mobile.json`
