### ISSUE TITLE
Newest version (0.6.0) splits arm & x86 on --release, any way to combine?

### ISSUE THREAD

**Issue by shanling** [MobileChromeApps/mobile-chrome-apps#547]
My apk is under 50mb for the playstore when combined, and I've been using the --release command to generate a combined apk for the past month or so, but I can no longer just generate one. Is there any way to recombine them into one apk? Or should I just be uploading two different apks to the playstore? Thanks.

**Comment by agrieve** [comment]
Highly recommend uploading two. Should be able to build just one with `cca build --release -- --gradleArg=-PcdvBuildMultipleApks=false`

**Comment by shanling** [comment]
Thanks!
