### ISSUE TITLE
Wrong sizes for all iOS icons in v0.6.0 

### ISSUE THREAD

**Issue by felixhammerl** [MobileChromeApps/mobile-chrome-apps#548]
Hi guys,

the iOS build completely messes up the icons ... they are all 180px (except the 60px icon).
Here's an excerpt from the manifest.mobile.json: 

```
{
    "ios": {
        "icons": {
            "29": "img/icon-29-ios.png",
            "40": "img/icon-40-ios.png",
            "50": "img/icon-50-ios.png",
            "57": "img/icon-57-ios.png",
            "58": "img/icon-58-ios.png",
            "60": "img/icon-60-ios.png",
            "72": "img/icon-72-ios.png",
            "76": "img/icon-76-ios.png",
            "80": "img/icon-80-ios.png",
            "87": "img/icon-87-ios.png",
            "100": "img/icon-100-ios.png",
            "114": "img/icon-114-ios.png",
            "120": "img/icon-120-ios.png",
            "144": "img/icon-144-ios.png",
            "152": "img/icon-152-ios.png",
            "180": "img/icon-180-ios.png"
        },
    },

    "android": {
        "icons": {
            "36": "img/icon-36-android.png",
            "48": "img/icon-48-android.png",
            "60": "img/icon-60-android.png",
            "72": "img/icon-72-android.png",
            "78": "img/icon-78-android.png",
            "96": "img/icon-96-android.png",
            "144": "img/icon-144-android.png",
            "192": "img/icon-192-android.png"
        },
    }
}
```

What am I doing wrong? According to your documentation, this should work... https://github.com/MobileChromeApps/mobile-chrome-apps/blob/master/docs/NextSteps.md#more-about-icons

Cheers
Felix

**Comment by agrieve** [comment]
Yikes! Could you paste the contents of your `config.xml` file? It should now have corresponding `<icon>` entries in it.

**Comment by shanling** [comment]
I'm having this same bug. When I cca prepare/build ios it doesn't seem to be copying the correct icon sizes to the iOS resources folder. It appears to be taking whatever your last icon in the icon list from manifest.json is and just copying that for every icon size. My config.xml says this:

    <icon src="www/img/icons/icon_180.png" />
    <icon src="www/img/icons/icon_29.png" width="29" />
    <icon src="www/img/icons/icon_36.png" width="36" />
    <icon src="www/img/icons/icon_40.png" width="40" />
    <icon src="www/img/icons/icon_48.png" width="48" />
    <icon src="www/img/icons/icon_57.png" width="57" />
    <icon src="www/img/icons/icon_58.png" width="58" />
    <icon src="www/img/icons/icon_72.png" width="72" />
    <icon src="www/img/icons/icon_76.png" width="76" />
    <icon src="www/img/icons/icon_78.png" width="78" />
    <icon src="www/img/icons/icon_80.png" width="80" />
    <icon src="www/img/icons/icon_87.png" width="87" />
    <icon src="www/img/icons/icon_96.png" width="96" />
    <icon src="www/img/icons/icon_120.png" width="120" />
    <icon src="www/img/icons/icon_152.png" width="152" />
    <icon src="www/img/icons/icon_180.png" width="180" />

and my manifest.json:

    "icons": {
        "29": "img/icons/icon_29.png",
        "36": "img/icons/icon_36.png",
        "40": "img/icons/icon_40.png",
        "48": "img/icons/icon_48.png",
        "57": "img/icons/icon_57.png",
        "58": "img/icons/icon_58.png",
        "72": "img/icons/icon_72.png",
        "76": "img/icons/icon_76.png",
        "78": "img/icons/icon_78.png",
        "80": "img/icons/icon_80.png",
        "87": "img/icons/icon_87.png",
        "96": "img/icons/icon_96.png",
        "120": "img/icons/icon_120.png",
        "152": "img/icons/icon_152.png",
        "180": "img/icons/icon_180.png"
    },

**Comment by felixhammerl** [comment]
I use this to do some post-build tweaks:

```
#!/bin/sh

# reads values from JSON
jsonValue() {
  KEY=$1
  num=$2
  awk -F"[,:}]" '{for(i=1;i<=NF;i++){if($i~/'$KEY'\042/){print $(i+1)}}}' | tr -d '"' | sed -n ${num}p
}

# go to root
cd `dirname $0`
cd ..

DIR=...
PROJNAME=`less dist/manifest.json | jsonValue name 1 | sed -e 's/^ *//' -e 's/ *$//'`

# create
rm -rf $DIR
mkdir -p $DIR
cca create ...

#prepare
cd ...
cca prepare

# 
# post-build tweaks
# 

echo ""
echo "## Running post-build tweaks"

# status bar should not overlay the web view
echo "Tweaking iOS status bar to not overlay the web view"
sed -i "" 's/StatusBarOverlaysWebView" value="true"/StatusBarOverlaysWebView" value="false"/' "platforms/ios/$PROJNAME/config.xml"

# status bar should use dark font on light background
echo "Tweaking iOS status bar to use dark font on light background"
sed -i "" 's/StatusBarStyle" value="lightcontent"/StatusBarStyle" value="darkcontent"/' "platforms/ios/$PROJNAME/config.xml"

# copy splash screens
echo "Copying splash screens"
cp ../../../src/img/Default* "platforms/ios/$PROJNAME/Resources/splash"

# fixing missing/wrong icons
echo "Fixing wrong/missing iOS icons"
cp ../../../src/img/icon-40-ios.png "platforms/ios/$PROJNAME/Resources/icons/icon-40.png"
cp ../../../src/img/icon-80-ios.png "platforms/ios/$PROJNAME/Resources/icons/icon-40@2x.png"
cp ../../../src/img/icon-120-ios.png "platforms/ios/$PROJNAME/Resources/icons/icon-40@3x.png"
cp ../../../src/img/icon-50-ios.png "platforms/ios/$PROJNAME/Resources/icons/icon-50.png"
cp ../../../src/img/icon-100-ios.png "platforms/ios/$PROJNAME/Resources/icons/icon-50@2x.png"
cp ../../../src/img/icon-60-ios.png "platforms/ios/$PROJNAME/Resources/icons/icon-60.png"
cp ../../../src/img/icon-120-ios.png "platforms/ios/$PROJNAME/Resources/icons/icon-60@2x.png"
cp ../../../src/img/icon-180-ios.png "platforms/ios/$PROJNAME/Resources/icons/icon-60@3x.png"
cp ../../../src/img/icon-72-ios.png "platforms/ios/$PROJNAME/Resources/icons/icon-72.png"
cp ../../../src/img/icon-144-ios.png "platforms/ios/$PROJNAME/Resources/icons/icon-72@2x.png"
cp ../../../src/img/icon-76-ios.png "platforms/ios/$PROJNAME/Resources/icons/icon-76.png"
cp ../../../src/img/icon-152-ios.png "platforms/ios/$PROJNAME/Resources/icons/icon-76@2x.png"
cp ../../../src/img/icon-29-ios.png "platforms/ios/$PROJNAME/Resources/icons/icon-small.png"
cp ../../../src/img/icon-58-ios.png "platforms/ios/$PROJNAME/Resources/icons/icon-small@2x.png"
cp ../../../src/img/icon-87-ios.png "platforms/ios/$PROJNAME/Resources/icons/icon-small@3x.png"
cp ../../../src/img/icon-57-ios.png "platforms/ios/$PROJNAME/Resources/icons/icon.png"
cp ../../../src/img/icon-114-ios.png "platforms/ios/$PROJNAME/Resources/icons/icon@2x.png"
```

**Comment by agrieve** [comment]
Thanks guys! I've identified and fixed the bug upstream:

https://issues.apache.org/jira/browse/CB-8832

Expect this to reach CCA in a couple of week.

@felixhammerl - thanks for sharing your awk & sed skillz!
