### ISSUE TITLE
Could not find property 'cdvPluginPostBuildExtras' on root project 'android'

### ISSUE THREAD

**Issue by tssweeney** [MobileChromeApps/mobile-chrome-apps#551]
Hello, I have identified a bug in the org.chromium.i18n plugin (I believe this is the root of the error). After updating to the latest cca and cordova via npm, I run the following command:
```cca create Bug && cd Bug && cca prepare && cca build android```
and am presented with the following error (after the ```build``` command is ran):
```
FAILURE: Build failed with an exception.

* Where:
Script '/Users/timothysweeney/Documents/SeniorProjectMaster/Bug/platforms/android/org.chromium.i18n/Bug-copy-locales.gradle' line: 7

* What went wrong:
A problem occurred evaluating script.
> Could not find property 'cdvPluginPostBuildExtras' on root project 'android'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2.426 secs

/Users/timothysweeney/Documents/SeniorProjectMaster/Bug/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error code 1 for command: /Users/timothysweeney/Documents/SeniorProjectMaster/Bug/platforms/android/gradlew with args: assembleDebug,-b,/Users/timothysweeney/Documents/SeniorProjectMaster/Bug/platforms/android/build.gradle,-Dorg.gradle.daemon=true,-x,lint,-x,lintVitalX86Release,-x,lintVitalArmv7Release,-x,compileLint,-x,copyReleaseLint,-x,copyDebugLint
ERROR building one of the platforms: Error: /Users/timothysweeney/Documents/SeniorProjectMaster/Bug/platforms/android/cordova/build: Command failed with exit code 1
You may not have the required environment or OS to build this project
```

Curious about this behavior on an un-doctored new project, I diffed a working, older project's 'platforms' directory and found that [projectRoot]/platforms/android/build.gradle contains an addition at line 54 ```apply from: 'org.chromium.i18n/TestCycle-copy-locales.gradle'```. After commenting out this line, my Bug app builds and runs on Android emulator and device.

Obviously this additional gradle file has a purpose and this is a hacky, momentary work-around. Any thoughts on a permanent fix?

Thank you,

Tim

**Comment by agrieve** [comment]
Sounds like your upgrade didn't pull in the newer version of cordova-android for some reason. I'd double check that the logs at the start of your output print out "cca v0.6.0"

**Comment by tssweeney** [comment]
Thank you for the reminder - you were correct, npm was failing to update due to a redundant copy in my bin folder. Again, thank you for your time!

Closing issue...
