### ISSUE TITLE
org.chromium.bootstrap plugin not recognizing org.chromium.backgroundapp plugin

### ISSUE THREAD

**Issue by PhilipGough** [MobileChromeApps/mobile-chrome-apps#558]
Having an issue where Cordova app coming to the foreground is not triggering the 'resume' event. Getting the error :
Uncaught TypeError: Cannot read property 'resumeType' of undefined

from line 61

      document.addEventListener('resume', function() {
        if (cordova.backgroundapp.resumeType == 'normal-launch') {
          fireOnLaunched();
        }
      });
Plugin list is as follows 
cca v0.6.0 :

cordova-plugin-whitelist 1.0.0-dev "Whitelist"
de.appplant.cordova.plugin.local-notification 0.8.2dev "LocalNotification"
org.apache.cordova.device 0.3.0 "Device"
org.apache.cordova.file 1.3.3 "File"
org.apache.cordova.inappbrowser 0.6.0 "InAppBrowser"
org.apache.cordova.network-information 0.2.15 "Network Information"
org.apache.cordova.statusbar 0.1.10 "StatusBar"
org.chromium.backgroundapp 1.0.0 "Background App"
org.chromium.bootstrap 2.0.4 "Chrome Apps Core"
org.chromium.cca-hooks 0.0.0 "undefined"
org.chromium.common 1.0.6 "Chrome Apps Common Utils"
org.chromium.i18n 2.0.0 "Chrome Apps I18n API"
org.chromium.navigation 1.0.2 "Chrome Apps Navigation"
org.chromium.polyfill.blob_constructor 1.0.1 "Blob constructor shim"
org.chromium.polyfill.customevent 1.0.3 "CustomEvent constuctor shim"
org.chromium.polyfill.xhr_features 1.0.2 "XHR Blob Response Type Polyfill"
org.chromium.runtime 1.1.0 "Chrome App Runtime"
org.chromium.storage 1.0.3 "Chrome Apps Storage API"
org.crosswalk.engine 0.0.1-dev "Crosswalk Engine"

Any ideas?
Thanks

**Comment by agrieve** [comment]
Merged in PR with the fix.
