### ISSUE TITLE
Using Karma for tests prevents android compilation

### ISSUE THREAD

**Issue by maxfurman** [MobileChromeApps/mobile-chrome-apps#560]
I added Karma and a few related addons for unit testing using npm. Now when I run `cca run android --emulator` I get the following error:

`Unable to add '/Users/Max/projects/vfi-track/VFI-Track/platforms/android/build/intermediates/assets/x86/debug/www/node_modules/karma/node_modules/log4js/node_modules/semver/semver.browser.js.gz': file already in archive (try '-u'?)
  	ERROR: unable to process assets while packaging '/Users/Max/projects/vfi-track/VFI-Track/platforms/android/build/intermediates/res/resources-x86-debug.ap_'
  	ERROR: packaging of '/Users/Max/projects/vfi-track/VFI-Track/platforms/android/build/intermediates/res/resources-x86-debug.ap_' failed
:processX86DebugResources FAILED`

I only need npm modules when I run my tests; I don't need them for device builds at all. Is there a way to exclude that folder from the build?

**Comment by agrieve** [comment]
Best way to exclude it is to not put it within the www/ directory.

**Comment by maxfurman** [comment]
The node_modules folder is copied into the www/ folder automatically by cca, so I don't have a choice there
