### ISSUE TITLE
./createproject.sh ChromeAppDevTool error

### ISSUE THREAD

**Issue by JimmyJune** [MobileChromeApps/mobile-chrome-apps#561]
when i run this:
./createproject.sh ChromeAppDevTool
it logs:
Installing "org.chromium.zip" for ios
+ [[ android ios = *android* ]]
+ cp plugins/org.apache.cordova.file/src/android/build-extras.gradle platforms/android/build-extras.gradle
cp: plugins/org.apache.cordova.file/src/android/build-extras.gradle: No such file or directory
where can i find this file?

**Comment by agrieve** [comment]
Thanks for bringing this up! Should be all fixed now. please re-open if anything is still failing for you
