### ISSUE TITLE
Allow loosening of CSP for remote image loading

### ISSUE THREAD

**Issue by wesleycho** [MobileChromeApps/mobile-chrome-apps#566]
This may be naive of me, but is there any reason why I cannot whitelist images for loosening CSP restrictions? Looking at [this block of code](https://github.com/MobileChromeApps/mobile-chrome-apps/blob/master/cca-manifest-logic/src/analyse-manifest.js#L159-L183), it would appear that it is not one of the options. Same for remote images for CSS (most notably for the `style-src` option).

**Comment by agrieve** [comment]
If you want it to work on desktop as well, then have a look at: https://github.com/GoogleChrome/apps-resource-loader

If you just want to loosen the CSP, you can completely override it via `"csp:" "foo"` within manifest.mobile.json

**Comment by wesleycho** [comment]
Ideally I just want to loosen it, since we support theming for our various clients at my company.

Thanks for the tip.
