### ISSUE TITLE
Oauth inappbrowser launch no longer working after updating from cca 0.5.1 to 0.7.0

### ISSUE THREAD

**Issue by infomofo** [MobileChromeApps/mobile-chrome-apps#572]
I just updated my local cca tool from 0.5.1 to 0.7.0 (I had to skip 0.6.0 due to the [icon issue](https://github.com/MobileChromeApps/mobile-chrome-apps/issues/553)).  The icon issue seems to have been resolved but some new issues seem to have been introduced, potentially related to the renaming of the cordova plugin frameworks.

While I'm not using the cordova inappbrowser plugin for anything in my code, I am using the oauth framework of chrome-mobile-apps, which I understand uses the inappbrowser under the covers to launch the oauth flow.  It works fine for me in cca 0.5.1.  However in 0.7.0, on an ios simulator, the oauth flow no longer launches, and the following error shows up on the debug console:

     module org.apache.cordova.inappbrowser.inappbrowser not found

Is there something I need to do to get oauth working again, or is this an undocumented bug introduced with 0.7.0?

**Comment by agrieve** [comment]
Published a new version of the plugin with this fix. Thanks for reporting and sorry for the breakage!

**Comment by infomofo** [comment]
thank you for this, @agrieve .  Can you clarify how to pick up this fix, or do I need to wait until 0.7.1 is released?

**Comment by agrieve** [comment]
Shouldn't need to wait. Try running "cca upgrade" to force all plugins to be updated.
