### ISSUE TITLE
failed version requirement: >=4.0.0-dev

### ISSUE THREAD

**Issue by felixhammerl** [MobileChromeApps/mobile-chrome-apps#581]
Hi guys,

my install fails with the message:
```
Plugin doesn't support this project's cordova-ios version. cordova-ios: 3.8.0, failed version requirement: >=4.0.0-dev
```

Problem is, cordova-ios isn't even released in this version... https://www.npmjs.com/package/cordova-ios

What do I do?

```
> node --version
v0.12.5
> cca --version
0.7.0
```

**Comment by agrieve** [comment]
Dupe of #580. I'll see if i can get it fixed today.
