### ISSUE TITLE
Samsung Galaxy S6 Chrome Does Not Support WebGL

### ISSUE THREAD

**Issue by jonobr1** [MobileChromeApps/mobile-chrome-apps#583]
Based on this reddit thread it looks like WebGL is disabled on the Galaxy S6's Google Chrome due to a lack of a specific extension: https://m.reddit.com/r/webgl/comments/354377/galaxy_s6_has_webgl_issues/

Is this something the Chromium build used in Mobile Chrome Apps can override / force? If so how do I go about doing this?

**Comment by clelland** [comment]
The Crosswalk port of Chromium that you can use in Mobile Chrome Apps should include WebGL support -- I haven't tried it specifically on an S6, but I don't think that should matter. If you choose to use it in your app, Crosswalk will completely replace the system web view.

**Comment by jonobr1** [comment]
I've tried it and it doesn't work on an S6 because of the Google Chrome issue posted in the reddit thread: https://code.google.com/p/chromium/issues/detail?id=470894

I can give you an APK if you're interested in trying it out.

**Comment by clelland** [comment]
Yeah, reading the reddit thread, it looks like it's Chromium that's disabling WebGL, on account of a (maybe) flaky GPU, and it's not something that Samsung has done in their port.

From a linked Chromium bug: "This is an issue with some Samsung devices not exposing an OpenGL extension that we require to safely expose WebGL."

One thing to try, from [the Intel Crosswalk FAQ](https://crosswalk-project.org/documentation/about/faq.html#Canvas-and-WebGL-support) is an `xwalk-command-line` in your assets directory. This can override the runtime flags for the webview, and you can disable the  WebGL GPU blacklist.

**Comment by jonobr1** [comment]
Ah, I'll give that a try. Thanks!

**Comment by jonobr1** [comment]
Unfortunately that didn't fix _my_ issue, but it may fix other people's. For clarity you write `xwalk --ignore-gpu-blacklist` in a file called `xwalk-command-line` in `/platforms/android/assets/`.

FYI, latest Samsung OS update fixes whatever extension that was missing from Chromium. :+1:
