### ISSUE TITLE
Audio API not working with Crosswalk

### ISSUE THREAD

**Issue by danny-mark** [MobileChromeApps/mobile-chrome-apps#585]
Audio playback in a simple demo app does not work from <audio> element or with JavaScript. The audio element appears, but doesn't seem to find the mp3 playable (has 0.00 length).

Running the app's code in mobile Chrome works fine. 

We've tested on two different Android devices, versions 4.4 and 5. 
Packaging with 'cca run android --device'.
Added permissions are RECORD_AUDIO, MODIFY_AUDIO_SETTINGS and CAPTURE_AUDIO_OUTPUT just in case.

**Comment by agrieve** [comment]
This is a sad known issue with android webviews :(.

A good work-around exists though - to use the webaudio api:

http://middleearmedia.com/web-audio-api-audio-buffer/
