### ISSUE TITLE
Crosswalk blink with windowSoftInputMode adjustResize

### ISSUE THREAD

**Issue by GustavoCostaW** [MobileChromeApps/mobile-chrome-apps#586]
Check the video:
 https://www.dropbox.com/s/wonh4jio91bkorl/File%20Mar%2015%2C%205%2035%2019%20PM.mov?dl=0 
    <preference name="android-windowSoftInputMode" value="adjustResize"/>

when I focus in input the web view redraw all element and generate this flicker Does anyone have any idea how to help me?

**Comment by Imskull** [comment]
My android app has same problem, it only happens on crosswalk+android5.0, it is ok on system webview+android5.0 and crosswalk+android4.0, it seems crosswalk dev team don't want us use crosswalk on android5.0, there are instructions how to build APKs for different platforms: https://github.com/MobileChromeApps/mobile-chrome-apps/blob/master/docs/Publish.md .

**Comment by GustavoCostaW** [comment]
Fix in crosswalk repo.
