### ISSUE TITLE
cca for windows 10?

### ISSUE THREAD

**Issue by Imskull** [MobileChromeApps/mobile-chrome-apps#590]
I just found cordova had [supported](http://blogs.msdn.com/b/visualstudio/archive/2015/04/30/introducing-the-windows-10-apache-cordova-platform.aspx) windows 10 now, any plan for cca supports windows 10?
something likes:
`cca platform add “windows@https://aka.ms/cordova-win10”` ?

thanks.

**Comment by agrieve** [comment]
We have no plans for this to be honest, but would happily accept patches to our plugins that add win10 support.

**Comment by Imskull** [comment]
It's ok, I will look into how feasible porting my chrome app to windows 10, hope it's less pain with cordova instead of node-webkit.

**Comment by Imskull** [comment]
Great news, just found node-webkit had supported Chrome App a month ago.
https://groups.google.com/forum/#!msg/nwjs-general/zeC6SedUSFY/BlumrYJeVHYJ

**Comment by agrieve** [comment]
That's really cool!
