### ISSUE TITLE
cca will delete the `xwalkVersion` when updating the config.xml

### ISSUE THREAD

**Issue by fujunwei** [MobileChromeApps/mobile-chrome-apps#592]
The latest [Crosswalk Cordova plugin](https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview) support default variables at install time. The `xwalkVersion` will be configured in the config.xml with hooks with default value, it will be deleted at uninstall time. so the cca need align with it.

You can also use following command to specify the version when installing the plugin
```
cordova plugin add cordova-plugin-crosswalk-webview --variable xwalkVersion="15+"
```
Don't delete the preference in the cca/node_modules/cca-manifest-logic/src/update-config-xml.js
```
if (analyzedManifest.engineName == 'crosswalk' && analyzedManifest.engineVer) {
      setOrCreatePreference('xwalkVersion', analyzedManifest.engineVer);
  } else {
      deletePreference('xwalkVersion');
  }
```

**Comment by dennice13** [comment]
Bye and wellcome to hello world by google

**Comment by dennice13** [comment]
Bye and wellcome to hello world by google

**Comment by Honry** [comment]
We can still reproduce this issue, anyone can help take a look? I will be very appreciate.

**Comment by agrieve** [comment]
For CCA apps, you can set the crosswalk version in the manifest.mobile.json file, so this behaviour is intended. I've updated the docs to mention how you do this.

**Comment by Honry** [comment]
This way can only specify Crosswalk stable version, what about Crosswalk beta?

**Comment by Honry** [comment]
@agrieve, could you please clarify if cca would support crosswalk beta configuration?
