### ISSUE TITLE
Error using chrome.storage.sync

### ISSUE THREAD

**Issue by vikasprogrammer** [MobileChromeApps/mobile-chrome-apps#596]
I am using the following code :

    chrome.storage.sync.get('Shops', function(retVal) {
     console.log(retVal);
    });

But I get this error: 

gopher://xxx/_generated_background_page.html

Rest of the app (which does not call `chrome.storage.sync` works perfectly fine). I am using AngularJS.

**Comment by agrieve** [comment]
chrome.storage.sync doesn't work. chrome.storage.local should work, and for syncing with drive you should use drive's JS API directly.
