### ISSUE TITLE
mobile chrome app does not work under ios10

### ISSUE THREAD

**Issue by chuqianyiding** [MobileChromeApps/mobile-chrome-apps#610]
I use the cca to wrap the HelloWorld chrome app and deploy it to ios. It works in ios 9.3 but it does not work in ios 10. It displays white screen with "Page load failed" . 
The problem comes from the plugin cordova-plugin-chrome-apps-bootstrap. 
In window.js, function exports.create, the XMLHttpRequest fail in ios 10 but succeed in ios 9.3. 
The requested url is in format "gopher://*/index.html"
Anybody have any idea how to solve this?

**Comment by Helidium** [comment]
I also need this resolved...

**Comment by chuqianyiding** [comment]
Helidium, I did the following but it still did not work in ios 10.

1. I add the <meta http-equiv="Content-Security-Policy" content="default-src * gap://ready file: data: blob: chrome-extension: gopher: gap:; connect-src *; media-src *; style-src file: data: blob: chrome-extension: gopher: gap: 'unsafe-inline';"> to index.html.
2. I add <access origin="*" /> to config.xml

**Comment by NicuAhmadi** [comment]
I also have the same exact problem!

**Comment by Helidium** [comment]
Yes I'm having the same problem, I ended up migrating to cordova instead...

**Comment by agrieve** [comment]
I think moving to Cordova directly is the right way forward here. You can
still use most mobile-chrome-apps plugins from a regular cordova project.

**Comment by chuqianyiding** [comment]
@Helidium , do you still keep all the plugins in plugins folder when you migrate to cordova?
I succeed in android but fail in ios. 

I did "cordova platform add ios" and open it in xcode. The problem comes from plugin cordova-plugin-chrome-apps-navigation.  I got error "arc semantic issue no visible @interface for UIView" for ChromeNavigation.m

**Comment by infomofo** [comment]
@agrieve Do you have a recommendation on best practices for such a migration?

Also, you said most plugins are usable- the ones I'm using are cordova-plugin-chrome-apps-identity and cordova-plugin-chrome-apps-system-storage - should i expect those to work outside the context of a chrome mobile app using just a normal cordova application?

Any guidance you could provide here would be helpful.

**Comment by ELundby45** [comment]
I was able to get a chrome mobile app to work on iOS 10 by adding a Content-Security-Policy override in manifest.mobile.json 

ie:
`"csp": "default-src file: data: blob: chrome-extension: gopher: gap:; connect-src * gopher: ws:; media-src *; style-src file: data: blob: chrome-extension: gopher: gap: 'unsafe-inline';"`

The particular thing that got things working for me: `connect-src * gopher:;`

**Comment by chuqianyiding** [comment]
@ELundby45 It worked. Thank you.
