### ISSUE TITLE
Content Security Policy (CSP) on iOS

### ISSUE THREAD

**Issue by tanx** [MobileChromeApps/mobile-chrome-apps#73]
Since iOS7 supports CSP by setting a meta tag in the html's head, I was able to use the following CSP in my old PhoneGap 2.5.0 app.

    <!DOCTYPE html>
    <html ng-app="mail" ng-csp>
      <head>
        ...

        
        <meta http-equiv="Content-Security-Policy" content="default-src 'self'; object-src 'none'; connect-src 'self' https://keys.whiteout.io https://keys-test.whiteout.io; img-src 'self' data:;">

        ...
      </head>
  
      <body key-shortcuts>...</body>
    </html>

Now that I'm porting my Chrome Packaged App with your great cca tool, the screen is just blank on startup.My guess is because the app doesn't link cordova.js in a script tag anymore like in the old PhoneGap 2.5.0 setup like so `<script src="cordova.js"></script>`, but rather the `cordova.js` and `cordova_plugins.js` files seem to be injected by the PhoneGap 3.3.0 runtime somehow.

So my question is if it's still possible to set CSP with this new setup and if so, which directives do I have to set in order to allow the injection of the cordova scripts. Thanks!

**Comment by agrieve** [comment]
Still working on updating the docs, but CSP is now supported and enabled by default in the latest version of `cca`!

**Comment by tanx** [comment]
Ok great!

**Comment by agrieve** [comment]
Also note that I've updated the docs at https://github.com/MobileChromeApps/mobile-chrome-apps/blob/master/docs/NextSteps.md to point out that the CSP is configurable:

* csp: When set, overrides the default Content-Security-Policy for apps
* cspUnsafeEval: Allow eval within Content-Security-Policy (default: false)
* cspUnsafeInline: Allow inline scripts within Content-Security-Policy (default: false)
